/*
 * User API's
 * Any Api's performed on User Level. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import java.io.File;
import io.swagger.client.model.SaleskenResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BulkUserApi
 */
@Ignore
public class BulkUserApiTest {

    private final BulkUserApi api = new BulkUserApi();

    /**
     * Create bulk user
     *
     * Use this Api to create bulk user with the help of excal file.Can be called from Super Admin Web App, Sales Manager Web App (User list page), User import page of sales manager integration workflow
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createBulkUserTest() throws ApiException {
        Integer orgId = null;
        File file = null;
        SaleskenResponse response = api.createBulkUser(orgId, file);

        // TODO: test validations
    }
}
