/*
 * User API's
 * Any Api's performed on User Level. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.User;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserApi
 */
@Ignore
public class UserApiTest {

    private final UserApi api = new UserApi();

    /**
     * Create user
     *
     * Use this API to create a new user. Can be called from Super Admin Web App, Sales Manager Web App (User list page), User import page of sales manager integration workflow.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createUserTest() throws ApiException {
        User body = null;
        User response = api.createUser(body);

        // TODO: test validations
    }
    /**
     * Delete user
     *
     * Use this API to delete the user. Can be called from Super Admin Web App, Sales Manager Web App (User list page), User import page of sales manager integration workflow.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteUserTest() throws ApiException {
        Long userId = null;
        User response = api.deleteUser(userId);

        // TODO: test validations
    }
    /**
     * Get all user List
     *
     * Use this API to get the user details with the help if email.Can be called from Super Admin Web App, Sales Manager Web App (User list page), User import page of sales manager integration workflow.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllUserTest() throws ApiException {
        Integer offset = null;
        Integer limit = null;
        List<User> response = api.getAllUser(offset, limit);

        // TODO: test validations
    }
    /**
     * Get User by id
     *
     * Use this API to get the user details with the help if user id.Can be called from Super Admin Web App, Sales Manager Web App (User list page), User import page of sales manager integration workflow.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserByIdTest() throws ApiException {
        Long userId = null;
        User response = api.getUserById(userId);

        // TODO: test validations
    }
    /**
     * Update user
     *
     * Use this API to update the user. Can be called from Super Admin Web App, Sales Manager Web App (User list page), User import page of sales manager integration workflow.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateUserTest() throws ApiException {
        Long userId = null;
        User body = null;
        User response = api.updateUser(userId, body);

        // TODO: test validations
    }
}
